version: '3.1'

services:
  db:
    container_name: split-the-bill-postgres-db
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: split-the-bill-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False' # DEV only (skip login window)
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False' # DEV only (skip login window)
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      
  server:
    container_name: split-the-bill-server
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./:/app

volumes:
  postgres-data:
  pgadmin-data: